pattern = 'v0.1.%d'
types = ["Cargo"]
message-template = "Created {version} for release."

[artifact.mac]
paths = {toolup = "artifacts/toolup-mac/toolup", toolup-shim = "artifacts/toolup-mac/toolup-shim"}
compress = { name = "toolup-mac.tar.gz", format = "tgz" }
target = "GitHub"

[artifact.linux]
paths = {toolup = "artifacts/toolup-linux/toolup", toolup-shim = "artifacts/toolup-linux/toolup-shim"}
compress = { name = "toolup-linux.tar.gz", format = "tgz" }
target = "GitHub"
