name: Publish Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-for-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos-x86, macos-aarch64]
        include:
        - build: linux
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
        - build: macos-x86
          os: macos-latest
          target: x86_64-apple-darwin
        - build: macos-aarch64
          os: macos-latest
          target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-release-${{ hashFiles('ci/cache-version') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
             ${{ runner.os }}-${{ matrix.target }}-cargo-release-${{ hashFiles('ci/cache-version') }}-
             ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('ci/cache-version') }}-
      - name: Install correct version of Rust
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            target: ${{ matrix.target }}
            override: true
      - name: Configure version and MacOs
        if: matrix.os == 'macos-latest'
        run: |
          mkdir ~/bin
          curl --location https://github.com/ethankhall/crom/releases/download/v0.4.2/crom-v0.4.2-darwin-x86_64.tgz | tar -xvz  -C ~/bin
          chmod +x ~/bin/crom
          ~/bin/crom write-version custom ${{ inputs.version }}
          brew install binutils
          echo "$(brew --prefix)/opt/binutils/bin" >> $GITHUB_PATH
      - name: Configure version and Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
          docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest write-version custom ${{ inputs.version }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target "${{ matrix.target }}"
      - run: |
          ls target/${{ matrix.target }}/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          if-no-files-found: error
          path: |
            target/${{ matrix.target }}/release/toolup
            target/${{ matrix.target }}/release/toolup-shim

  release:
    runs-on: ubuntu-latest
    needs: build-for-os
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: aarch64-apple-darwin
          path: artifacts/aarch64-apple-darwin
      - uses: actions/download-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: artifacts/x86_64-apple-darwin
      - uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu
          path: artifacts/x86_64-unknown-linux-gnu
      - name: Create release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          ls artifacts/*/*
          mkdir artifacts-to-publish
          tar -czv --strip-components 1 --owner=0 --group=0 --no-same-owner -f artifacts-to-publish/toolup-${{ inputs.version }}-linux-gnu-x86_64.tgz -C artifacts/x86_64-unknown-linux-gnu toolup toolup-shim
          tar -czv --strip-components 1 --owner=0 --group=0 --no-same-owner -f artifacts-to-publish/toolup-${{ inputs.version }}-darwin-aarch64.tgz -C artifacts/aarch64-apple-darwin toolup toolup-shim
          tar -czv --strip-components 1 --owner=0 --group=0 --no-same-owner -f artifacts-to-publish/toolup-${{ inputs.version }}-darwin-x86_64.tgz -C artifacts/x86_64-apple-darwin toolup toolup-shim
          gh release upload ${{ inputs.version }} artifacts-to-publish/*
