name: Publish Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-
            ${{ runner.os }}-cargo-
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: update version
        run: |
          docker run --rm -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest write-version custom ${{ inputs.version }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: |
            target/release/toolup
            target/release/toolup-shim

  build-mac:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
             ${{ runner.os }}-${{ matrix.target }}-cargo-release-
             ${{ runner.os }}-${{ matrix.target }}-cargo-
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            target: ${{ matrix.target }}
      - name: update version
        run: |
          mkdir ~/bin
          curl --location https://github.com/ethankhall/crom/releases/download/v0.3.4/crom-mac.tar.gz | tar -xvz  -C ~/bin
          chmod +x ~/bin/crom
          ~/bin/crom write-version custom ${{ inputs.version }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            target/release/toolup
            target/release/toolup-shim

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-mac
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: aarch64-apple-darwin
          path: artifacts/aarch64-apple-darwin
      - uses: actions/download-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: artifacts/x86_64-apple-darwin
      - uses: actions/download-artifact@v3
        with:
          name: linux-artifacts
          path: artifacts/linux
      - name: login to registry
        run: docker login docker.pkg.github.com --username ethankhall --password ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        run: |
          docker run --rm -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/target docker.pkg.github.com/ethankhall/crom/cli:latest upload-artifacts custom --artifact-path=./artifacts --version ${{ inputs.version }} linux mac-x86 mac-aarch64
